//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarProject.DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_orders()
        {
            this.Client_order_details = new HashSet<Client_order_details>();
        }
    
        public int id { get; set; }
        public int spot_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> order_time { get; set; }
        public Nullable<System.DateTime> payment_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_order_details> Client_order_details { get; set; }
        public virtual User User { get; set; }
        public virtual Spot Spot { get; set; }
    }
}
