//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarProject.DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_order_details_pretty
    {
        public int id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> required_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string employee_username { get; set; }
        public string supplier_name { get; set; }
        public string location_name { get; set; }
        public string name { get; set; }
        public string category_name { get; set; }
        public decimal purchase_price { get; set; }
        public short quantity { get; set; }
    }
}
