//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarProject.DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_order_details
    {
        public int warehouse_order_id { get; set; }
        public int product_id { get; set; }
        public decimal unit_price { get; set; }
        public short quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse_orders Warehouse_orders { get; set; }
    }
}
