//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarProject.DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workstations_with_rights_pretty
    {
        public int workstation_id { get; set; }
        public string workstation_name { get; set; }
        public byte employe_permissions { get; set; }
        public int id { get; set; }
        public string location_name { get; set; }
        public string city { get; set; }
    }
}
